### PR TITLE
Fix Bolt support

### LINKED ISSUE #20: Bolt driver compatibility!?
Hello,
Do you have any plans of adding bolt driver compatibility?

Thanks!

### PR DESCRIPTION
**Pull request by johannessen**
Resolves #20 (for real this time).

This doesn’t address #28, majensen/perlbolt#38, or johannessen/neo4j-driver-perl#11. Other than that, the test suite succeeds now on my system. And yes, this time I did double-check that it actually used Bolt.

- - -

Sorry that automatic merging isn’t possible. I’m afraid the CI workflow changes you made today prevent me from updating my fork. I keep getting a message saying `refusing to allow an OAuth App to create or update workflow '.github/workflows/test.yml' without 'workflow' scope`, but I’m not even using OAuth.

Could be a bug in GitHub, but I lack the time to investigate it further.

### CODE REVIEW

**Comment by majensen** [comment]
Hey Arne - I'm going to figure how to make the CI work for you (ideally for everyone); still in "beta" :-)

Really appreciate you putting the finishing touches on this.

**Comment by majensen** [comment]
@johannessen One thing to do -- go ahead and branch directly in the repo, since you're allowed

**Comment by majensen** [comment]
One thing - I want to leave in 0012_connect.t and its data files. This test mocks the server and the data files are fake responses. It was borking, but I fixed that in 331c68e6945d211acebc9bf2f0f49013db28f8b3. Can you pull and just patch ...Neo4j::Driver?

**Comment by johannessen** [comment]
Well, I made a bit of a mess with #27. Helping to clean it up is the least I can do.

About `0012_connect.t` – the mocking is very nicely done, but after 9589d0e85c678d0dc44751fe234c574c3be45ba0, it looked like a no-op to me. I may have misunderstood how that test works though, being less familiar with the Neo4p code than you are, obviously.

Anyway, I have now removed that particular commit and kept the other one.

**Comment by johannessen** [comment]
> Hey Arne - I'm going to figure how to make the CI work for you (ideally for everyone); still in "beta" :-)

Right. Pushing to my fork succeeds again now – not really sure why. Maybe a config snafu on my end, or GH fixed something on theirs.

FYI, unlike Travis, the GH workflow also tries to run in forks, but fails, apparently because `$DOCKERH` is unset.

https://github.com/johannessen/rest-neo4p/runs/1808494080

**Comment by majensen** [comment]
Yeah that's tells me that actions won't use my envs on your fork, even if you're requesting a pull into my repo. Which I guess is ok, but this is a situation where I want my canned action, including its "secret" resources, to run on anybody's PR, which I would think is a reasonable and common use case. 🤷‍♂️

**Pull request merged**
