### PR TITLE
Add support for Bolt to version pre-check

### LINKED ISSUE #20: Bolt driver compatibility!?
Hello,
Do you have any plans of adding bolt driver compatibility?

Thanks!

### LINKED ISSUE #26: Unauthorized on connect to Neo4j 2/3
Two different failure modes exist in REST::Neo4p 0.4000 when connecting to Neo4j version 2 or 3:

````perl
REST::Neo4p->connect("http://$host:7474", $user, $password);
# LWP::UserAgent   dies:  On version pre-check: 401 Unauthorized at …/REST/Neo4p.pm line 175.
# Mojo::UserAgent  dies:  On version pre-check: 401 Unauthorized at …/REST/Neo4p.pm line 175.
# HTTP::Thin       dies:  Internal Exception
# Neo4j::Driver    dies:  On version pre-check: 401 Unauthorized at …/REST/Neo4p.pm line 175.
````

````perl
REST::Neo4p->connect("http://$user:$password\@$host:7474");
# LWP::UserAgent   dies:  Unauthorized (connect phase 2)
# Mojo::UserAgent  dies:  Unauthorized (connect phase 2)
# HTTP::Thin       dies:  Internal Exception
# Neo4j::Driver    works!
````

The workaround is to specify the credentials twice like this:

````perl
REST::Neo4p->connect("http://$user:$password\@$host:7474", $user, $password);
# LWP::UserAgent   works!
# Mojo::UserAgent  works!
# HTTP::Thin       dies:  Internal Exception
# Neo4j::Driver    works!
````

(Not sure what is going on with `HTTP::Thin`. Haven’t bothered to investigate further.)

### PR DESCRIPTION
**Pull request by johannessen**
Resolves #20.

Also fixes #26.

You may need to change or remove `0012_connect.t` (though it does succeed locally on my system).

### CODE REVIEW

**Comment by majensen** [comment]
@johannessen - just saw this again (doh) - I will put this on my to-do list 
Looks like I need to update the CI here to avoid pulling images from Docker (they have severely limited the number of free pulls). Need to fix that to get a real readout from the tests.

**Comment by johannessen** [comment]
Right. As you know, my CI setup is slightly different that yours. Sorry I couldn’t help with the Docker problem!

**Comment by majensen** [comment]
Maybe Travis is borking; I had already gone to my private docker repo and it had been working. :| 
Fiddling with it.

**Comment by johannessen** [comment]
Uh-oh. I think I need to apologise. #26 _is_ resolved, but #20 is not. I did try and execute the test suite via Bolt before I opened the PR, but it must have accidentally used HTTP instead. My bad!

At first glance, it appears that several failures happen because the `agent->{_actions}` aren’t hard-coded in your Neo4j::Driver agent. The old REST actions simply aren’t available through Bolt (nor through Jolt for that matter). IIRC we already talked about this a while back.

There’s also a problem with UTF-8 and another one with constraints. Shouldn’t be too difficult to track down. I’ll look into both, but may not get around to it until next week.

**Pull request merged**
